# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloFreshTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HelloFreshTest
  pod 'SDWebImage', '4.0'

  target 'HelloFreshTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
